### ISSUE TITLE
About application to glTF animation

### ISSUE THREAD

**Issue by niuin** [stevinz/three-subdivide#1]
Hello.
I found it a great project.
But would it be difficult to apply it to glTF animation?

my code:
```js
  // Morphing Animation at the top of the screen
  gltfMesh = gltf.scene.children[ 0 ];
  gltfMesh.scale.set( 1.5, 1.5, 1.5 );
  gltfMesh = gltf.scene;
  originalGeometry = gltfMesh.children[0].geometry;
  scene.add( gltfMesh );
  mixer = new THREE.AnimationMixer( gltfMesh );
  mixer.clipAction( gltf.animations[ 1 ] ).setDuration( 5 ).play();
  
  
  // Mesh with subdivisions applied at the bottom of the screen
  const geometry = LoopSubdivision.modify(originalGeometry);
  const material = new THREE.MeshNormalMaterial();
  const gltfMesh_sub = new THREE.Mesh(geometry, material);
  scene.add( gltfMesh_sub );					
  mixer_sub = new THREE.AnimationMixer( gltfMesh_sub );
  mixer_sub.clipAction( gltf.animations[ 1 ] ).setDuration( 5 ).play();
```

https://user-images.githubusercontent.com/868060/185723390-98f9d10b-3e14-43cd-a74d-4f8658efa171.mp4
To me it looks like the keyframe animation is disappearing.

What I am trying to do is
[https://threejs.org/examples/webgl_morphtargets_horse.html](https://threejs.org/examples/webgl_morphtargets_horse.html)
I am trying to apply a subdivision surface to an animation like this sample

**Comment by stevinz** [comment]
This library was created with static geometry in mind. Currently there is no processing of morphAttributes. The animation is disappearing because the morphAttributes are dropped (never added) in the modified geometry.

However, it would be nice to support. I will look into it and see how much work it will be to add. I'll get back to you in a couple days.

**Comment by stevinz** [comment]
Okay, I managed to implement morph targets into the subdivision algorithm. I have updated the library to version 1.1.0 on Github and NPM with the changes.

You can see a demo here:
https://stevinz.github.io/three-subdivide/MorphTargets.html

Let me know if this works for you.

**Comment by niuin** [comment]
Very nice!
Thank you for your interest.

I tried it in my environment.
Simple glTFs like Horse, Flamingo, Pratto, etc. work,
But some of the models seem not to be loaded.

```javascript
const geometry = LoopSubdivision.modify( mesh.geometry, 2 );
```
The geometry is being returned with a type error in this section.
What could be the cause?

from Chrome
```console
LoopSubdivision.js:764 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isBufferGeometry')
    at verifyGeometry (LoopSubdivision.js:764:20)
    at LoopSubdivision.modify (LoopSubdivision.js:135:15)
    at webgl_morphtargets_horse.html:125:39
    at GLTFLoader.js:207:6
    at GLTFLoader.js:2502:5
```

![subd](https://user-images.githubusercontent.com/868060/186309976-9c4281ef-654e-4e94-9bfa-47990fb9cd68.jpg)

**Comment by stevinz** [comment]
That error is saying the geometry passed into the LoopSubdivision.modify() function was undefined. It may be a problem with the loader and / or model file and not with the modifier.

Do you have a link to a model that causes this error so that I can troubleshoot further?

**Comment by niuin** [comment]
Thank you for your reply.

I tried many times with different output settings but could not figure out the cause.

I have uploaded the glTF model.
It is created in Blender.
[http://niu.re/t/t2.glb](http://niu.re/t/t2.glb)

I also prepared a working page.
[http://niu.re/t/test.html](http://niu.re/t/test.html)


When I replace the loading with this code with the Horse model.
I have confirmed that it is applied without error.

**Comment by stevinz** [comment]
Okay, thanks, I see the problem. The model you are using is loaded as a parent object with several child meshes. The parent object has no geometry, the children meshes contain the geometries. This library is designed to operate only directly on `BufferGeometry`, not on `Object3D`, `Mesh`, `Group`, etc. It is up to the programmer to apply it as needed to children meshes.

The following code works on the model you sent. It loops through the loaded `Group` and applies subdivision to the children geometries. This code may need to be modified for other models, depending on the internal hierarchy of the model.

Side note, the animation you sent has a lot of keyframes. Subdivision must be applied on each frame, so it is slow to load. I don't know your use case, but it may be better to smooth the geometry within Blender instead of using this library. Or, if you wish to use this library, after you have subdivided the geometries, save back out the model so you don't have to call subdivision every time you load your models. Just a thought...


``` javascript
const loader = new GLTFLoader();
loader.load( 't2.glb', function ( gltf ) {

	///// Original Mesh

	mesh = gltf.scene.children[ 0 ];

	scene.add( mesh );
	mixer = new THREE.AnimationMixer( mesh );
	mixer.clipAction( gltf.animations[ 1 ] ).play();

	///// Subdivided Mesh

	const mesh_subdivided = new THREE.Group();

	for (let i = 0; i < mesh.children.length; i ++ ) {

		const params = {
			split: false, // optional, default: true
			preserveEdges: true, // optional, default: false
		};

		const geometry = LoopSubdivision.modify( mesh.children[i].geometry, 1, params );
		const material = mesh.children[i].material.clone();

		const child_mesh = new THREE.Mesh( geometry, material );
		child_mesh.name = mesh.children[i].name;

		mesh_subdivided.add( child_mesh );

	}

	mesh_subdivided.position.x = 50;
	scene.add( mesh_subdivided  );

	mixer_sub = new THREE.AnimationMixer( mesh_subdivided );
	mixer_sub.clipAction( gltf.animations[ 1 ] ).play();

} );
```

**Comment by niuin** [comment]
Thank you for taking the time to help us.

I have confirmed that it works well here as well.

I did not apply SubDivisionSuface in Blender because
Because the file size is dozens of times larger.

So I needed a way to apply it on the web.
But as you pointed out, the number of vertices is still being adjusted.
We would like to make the load appropriate.

I now have more options.
Thank you for the great library.
